# Generated by Django 4.0.4 on 2022-04-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='poll_choices', to='mypolls.choices'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_parent', to='mypolls.polls'),
        ),
    ]
