# Generated by Django 4.0.4 on 2022-04-23 19:12

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mypolls', '0006_alter_user_token_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='choice_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 23, 19, 12, 21, 21692, tzinfo=utc)),
        ),
    ]
